app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'
urlpatterns=[
    path('friend1/',friend1,name='friend1')
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'
urlpatterns=[
    path('Institute_emp/',Institute_emp,name='Institute_emp')
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
from app3.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('jspiders/',jspiders,name='jspiders')
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def friend1(request):
    return render(request,'friend1.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def Institute_emp(request):
    return render(request,'Institute_emp.html')

app3/views.py
from django.shortcuts import render

# Create your views here.

def jspiders(request):
    return render(request,'jspiders.html')

templates/Institute_emp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>We will give Breef Details about Jspiders Institute</h1>
        <h1>Course fee will be starting from 35k</h1>
        <a href="{% url 'jspiders' %}"><h1>Click Here to get information about classes</h1></a>
    </center>
</body>
</html>

templates/friend1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>I am Suggesting you to join in Jspiders Institute</h1>
        <h1>For that you want to meet Institute Employees in Office Room</h1>
        <a href="{% url 'app2:Institute_emp' %}"><h1>To Visit Institute Please Click Here</h1></a>
    </center>
</body>
</html>

templates/jspiders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>You choosed Python as a main streem</h1>
        <h1>For python we have two trainers 
            1.Santosh
            2.Harshad
        </h1>
        <h1>Your Class timenge starts at 10:30 AM Everyday</h1>
        <a href="{% url 'app1:friend1' %}"><h1>If you are not intrested to join here , Thank you for consulting us</h1></a>
    </center>
</body>
</html>